# Generated by Django 4.1.5 on 2023-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_adult_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='a',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
