# Generated by Django 4.1.5 on 2023-03-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
