# Generated by Django 4.1.5 on 2023-03-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_booking_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='a',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_cost',
        ),
    ]
