# Generated by Django 4.1.5 on 2023-03-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_booking_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(blank=True, default=None, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='booking.reservation')),
            ],
        ),
    ]
