# Generated by Django 4.1.5 on 2023-04-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0007_cancelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservee",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
