# Generated by Django 4.1.5 on 2023-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_reservation_cancelled_alter_reservation_reservee"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
