# Generated by Django 4.1.7 on 2023-05-05 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0011_reservation_cancellation_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_reservee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservees', to=settings.AUTH_USER_MODEL),
        ),
    ]
