# Generated by Django 4.1.5 on 2023-05-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_reservation_guest_reservee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cancelled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
