# Generated by Django 4.1.5 on 2023-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClubRepresentative",
        ),
    ]
