# Generated by Django 4.1.5 on 2023-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_delete_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="poster_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
