# Generated by Django 4.1.5 on 2023-03-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0005_film_poster_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="showing",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),

    ]
