# Generated by Django 4.1.5 on 2023-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_showing_end_time_alter_film_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='avalible_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
