# Generated by Django 4.1.7 on 2023-03-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priceID',
        ),
    ]
