# Generated by Django 4.1.5 on 2023-04-16 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0011_alter_ticket_productid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showing",
            old_name="avalible_seats",
            new_name="available_seats",
        ),
    ]
