# Generated by Django 4.1.5 on 2023-04-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0012_rename_avalible_seats_showing_available_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinema",
            name="ticket_price",
        ),
        migrations.AddField(
            model_name="showing",
            name="adult_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="showing",
            name="child_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="showing",
            name="student_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
