# Generated by Django 4.1.7 on 2023-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_remove_cinema_ticket_price_showing_adult_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('15', '15'), ('18', '18')], default='U', max_length=3),
        ),
    ]
