# Generated by Django 4.1.7 on 2023-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_film_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='productID',
            new_name='id',
        ),
    ]
