# Generated by Django 4.1.7 on 2023-04-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_rename_productid_ticket_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
