# Generated by Django 4.1.5 on 2023-04-23 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0015_remove_showing_adult_price_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
