# Generated by Django 4.1.5 on 2023-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0016_delete_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="showing",
            name="covid_capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="showing",
            name="last_seat_number_assigned",
            field=models.IntegerField(default=0),
        ),
    ]
