# Generated by Django 4.1.7 on 2023-04-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='child_discount_rate',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='student_discount_rate',
        ),
    ]
