# Generated by Django 4.1.7 on 2023-04-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_remove_cinema_child_discount_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketType',
            new_name='ticket_type',
        ),
    ]
