# Generated by Django 4.1.7 on 2023-04-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_showing_covid_capacity_and_more'),
        ('cinema', '0019_rename_tickettype_ticket_ticket_type'),
    ]

    operations = [
    ]
