# Generated by Django 4.1.7 on 2023-05-04 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_remove_film_genre_film_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='seating_capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
