# Generated by Django 4.1.5 on 2023-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0022_alter_screen_screen_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="showing",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="film",
            name="length",
            field=models.DurationField(),
        ),
    ]
