# Start with the official PostgreSQL image
FROM postgres:13

# Set the environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=uweflix_db
ENV POSTGRES_HOST_AUTH_METHOD=trust

# Expose port 5432 to the host
EXPOSE 5432
