# Generated by Django 4.1.7 on 2023-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentdiscountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripeCustomerID',
            field=models.CharField(default='', max_length=255),
        ),
    ]
