# Generated by Django 4.1.5 on 2023-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_alter_club_representative"),
    ]

    operations = [
    ]
