# Generated by Django 4.1.5 on 2023-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0003_clubrepresentative_password"),
    ]

    operations = [

    ]
