# Generated by Django 4.1.5 on 2023-04-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_club_active"),
    ]

    operations = [

    ]
